python3 PSFConvolution_Trilinear_IDW.py rocks human-eye 4.0
python3 PSFConvolution_Trilinear_IDW.py rocks human-eye 8
python3 PSFConvolution_Trilinear_IDW.py rocks human-eye 11
python3 PSFConvolution_Trilinear_IDW.py rocks canon-zoom 1.4
python3 PSFConvolution_Trilinear_IDW.py rocks canon-zoom 5.6
python3 PSFConvolution_Trilinear_IDW.py rocks canon-zoom 11
python3 PSFConvolution_Trilinear_IDW.py rocks petzval 1.4
python3 PSFConvolution_Trilinear_IDW.py rocks petzval 5.6
python3 PSFConvolution_Trilinear_IDW.py rocks petzval 11
python3 PSFConvolution_Trilinear_IDW.py rocks itoh-zoom 1.4
python3 PSFConvolution_Trilinear_IDW.py rocks itoh-zoom 5.6
python3 PSFConvolution_Trilinear_IDW.py rocks itoh-zoom 11
python3 PSFConvolution_Trilinear_IDW.py rocks double-gauss 1.4
python3 PSFConvolution_Trilinear_IDW.py rocks double-gauss 5.6
python3 PSFConvolution_Trilinear_IDW.py rocks double-gauss 11
python3 PSFConvolution_Trilinear_IDW.py rocks kreitzer-tele 1.4
python3 PSFConvolution_Trilinear_IDW.py rocks kreitzer-tele 2.8
python3 PSFConvolution_Trilinear_IDW.py rocks kreitzer-tele 4.0

python3 PSFConvolution_Trilinear_IDW.py field human-eye 4.0
python3 PSFConvolution_Trilinear_IDW.py field human-eye 8
python3 PSFConvolution_Trilinear_IDW.py field human-eye 11
python3 PSFConvolution_Trilinear_IDW.py field canon-zoom 1.4
python3 PSFConvolution_Trilinear_IDW.py field canon-zoom 5.6
python3 PSFConvolution_Trilinear_IDW.py field canon-zoom 11
python3 PSFConvolution_Trilinear_IDW.py field petzval 1.4
python3 PSFConvolution_Trilinear_IDW.py field petzval 5.6
python3 PSFConvolution_Trilinear_IDW.py field petzval 11
python3 PSFConvolution_Trilinear_IDW.py field itoh-zoom 1.4
python3 PSFConvolution_Trilinear_IDW.py field itoh-zoom 5.6
python3 PSFConvolution_Trilinear_IDW.py field itoh-zoom 11
python3 PSFConvolution_Trilinear_IDW.py field double-gauss 1.4
python3 PSFConvolution_Trilinear_IDW.py field double-gauss 5.6
python3 PSFConvolution_Trilinear_IDW.py field double-gauss 11
python3 PSFConvolution_Trilinear_IDW.py field kreitzer-tele 1.4
python3 PSFConvolution_Trilinear_IDW.py field kreitzer-tele 2.8
python3 PSFConvolution_Trilinear_IDW.py field kreitzer-tele 4.0

python3 PSFConvolution_Trilinear_IDW.py tree human-eye 4.0
python3 PSFConvolution_Trilinear_IDW.py tree human-eye 8
python3 PSFConvolution_Trilinear_IDW.py tree human-eye 11
python3 PSFConvolution_Trilinear_IDW.py tree canon-zoom 1.4
python3 PSFConvolution_Trilinear_IDW.py tree canon-zoom 5.6
python3 PSFConvolution_Trilinear_IDW.py tree canon-zoom 11
python3 PSFConvolution_Trilinear_IDW.py tree petzval 1.4
python3 PSFConvolution_Trilinear_IDW.py tree petzval 5.6
python3 PSFConvolution_Trilinear_IDW.py tree petzval 11
python3 PSFConvolution_Trilinear_IDW.py tree itoh-zoom 1.4
python3 PSFConvolution_Trilinear_IDW.py tree itoh-zoom 5.6
python3 PSFConvolution_Trilinear_IDW.py tree itoh-zoom 11
python3 PSFConvolution_Trilinear_IDW.py tree double-gauss 1.4
python3 PSFConvolution_Trilinear_IDW.py tree double-gauss 5.6
python3 PSFConvolution_Trilinear_IDW.py tree double-gauss 11
python3 PSFConvolution_Trilinear_IDW.py tree kreitzer-tele 1.4
python3 PSFConvolution_Trilinear_IDW.py tree kreitzer-tele 2.8
python3 PSFConvolution_Trilinear_IDW.py tree kreitzer-tele 4.0
